### ISSUE TITLE
Add Rails 6.0.5 Support to Core Components

### ISSUE THREAD

**Issue by tpendragon** [samvera/maintenance#28]
- [x] Browse Everything - released 1.1.2
- [x] hydra-editor https://github.com/samvera/hydra-editor/issues/184 work underway in https://github.com/samvera/hydra-editor/pull/192
- [x] hydra-file_characterization - released in 1.1.2
- [x] hydra-head - released 12.0.0
- [x] hydra-pcdm (not released but only tests needed to be changed; PR: https://github.com/samvera/hydra-pcdm/pull/277)
- [x] hydra-role-management released in 1.0.3
- [x] hydra-works - released 2.0.0
- [x] hydra-derivatives - released 3.6.0
- [x] iiif_manifest (not released but only tests needed to be changed; PR: https://github.com/samvera/iiif_manifest/pull/45)
- [x] ldp - tested in release 1.0.1 
- [x] noid-rails (not released but only tests needed to be changed; PR: https://github.com/samvera/noid-rails/pull/95)
- [x] questioning_authority - released in 5.4 and backported to 2.3
- [x] rubydora - (not released but only tests needed to be changed; PR: https://github.com/samvera/rubydora/pull/131)
