### ISSUE TITLE
Support Rails 6.1.6 releases for Core Components

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/maintenance#76]
- [x] [active_fedora](https://github.com/samvera/active_fedora)
- [x] [bixby](https://github.com/samvera/bixby)
- [x] browse-everything (https://github.com/samvera/browse-everything/issues/372)
- [x] hydra-derivatives (https://github.com/samvera/hydra-derivatives/issues/233)
- [x] hydra-editor (https://github.com/samvera/hydra-editor/issues/199)
- [x] hydra-file_characterization (https://github.com/samvera/hydra-file_characterization/issues/58)
- [x] hydra-head (https://github.com/samvera/hydra-head/issues/543)
- [x] hydra-pcdm (https://github.com/samvera/hydra-pcdm/issues/285)
- [x] hydra-role-management (https://github.com/samvera/hydra-role-management/issues/64)
- [x] hydra-works (https://github.com/samvera/hydra-works/issues/381)
- [x] iiif_manifest (https://github.com/samvera/iiif_manifest/issues/60)
- [x] ldp (https://github.com/samvera/ldp/issues/130)
- [x] noid-rails (https://github.com/samvera/noid-rails/issues/110)
- [x] questioning_authority (https://github.com/samvera/questioning_authority/issues/344)
- [x] rubydora (https://github.com/samvera/rubydora/issues/138)
- [x] [samvera.github.io](https://github.com/samvera/samvera.github.io)
- [x] [samvera-circleci-orb](https://github.com/samvera/samvera-circleci-orb)
- [x] [valkyrie](https://github.com/samvera/valkyrie) (https://github.com/samvera/valkyrie/pull/896)
