### ISSUE TITLE
Support Ruby 3.0.5

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/maintenance#77]
- [x] [active_fedora](https://github.com/samvera/active_fedora) (https://github.com/samvera/active_fedora/issues/1470) (Draft PR: https://github.com/samvera/active_fedora/pull/1489)
- [x] [bixby](https://github.com/samvera/bixby)
- [x] browse-everything (https://github.com/samvera/browse-everything/issues/373)
- [x] hydra-derivatives (https://github.com/samvera/hydra-derivatives/issues/234) (Draft PR: https://github.com/samvera/hydra-derivatives/pull/248)
- [x] hydra-editor (https://github.com/samvera/hydra-editor/issues/200) (Draft PR: https://github.com/samvera/hydra-editor/pull/216)
- [x] hydra-file_characterization (https://github.com/samvera/hydra-file_characterization/issues/59)
- [x] hydra-head (https://github.com/samvera/hydra-head/issues/544) (Draft PR: https://github.com/samvera/hydra-head/pull/553)
- [x] hydra-pcdm (https://github.com/samvera/hydra-pcdm/issues/286) (Draft PR: https://github.com/samvera/hydra-pcdm/pull/295)
- [x] hydra-role-management (https://github.com/samvera/hydra-role-management/issues/65) (Draft PR: https://github.com/samvera/hydra-role-management/pull/74)
- [x] hydra-works (https://github.com/samvera/hydra-works/issues/382) (Draft PR: https://github.com/samvera/hydra-works/pull/394)
- [x] iiif_manifest (https://github.com/samvera/iiif_manifest/issues/61)
- [x] ldp (https://github.com/samvera/ldp/pull/149)
- [x] noid-rails (https://github.com/samvera/noid-rails/issues/111) (PR: https://github.com/samvera/noid-rails/pull/115)
- [x] questioning_authority (https://github.com/samvera/questioning_authority/issues/345)
- [x] rubydora (https://github.com/samvera/rubydora/issues/139)
- [x] [samvera.github.io](https://github.com/samvera/samvera.github.io)
- [x] [samvera-circleci-orb](https://github.com/samvera/samvera-circleci-orb)
- [x] [valkyrie](https://github.com/samvera/valkyrie)

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/ldp/issues/131 is currently blocking  https://github.com/samvera/active_fedora/issues/1470 and https://github.com/samvera/hydra-editor/issues/200

**Comment by jrgriffiniii** [comment]
Please find the release notes for 3.0.5 at the following: https://www.ruby-lang.org/en/news/2022/11/24/ruby-3-0-5-released/

**Comment by cjcolvar** [comment]
Draft PRs for ActiveFedora and Hydra-Head are ready waiting on ActiveTriples getting support for ruby 3.0.  There is a draft PR on a fork that @jrgriffiniii made which these draft PRs are using (https://github.com/samvera-labs/ActiveTriples/pull/8).  We need to figure out how to get these changes into ActiveTriples and a release cut.  Probably the first question to answer is which repo, gitlab or github, is the canonical source for ActiveTriples?  Next would be who has permission to merge changes and cut releases?
