### ISSUE TITLE
Maintenance Roadmap for ActiveTriples

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/maintenance#88]
Given that an update made to https://github.com/ActiveTriples/ActiveTriples is going to block an update supporting Ruby 3.0.z releases for active_fedora (please see https://github.com/samvera/active_fedora/issues/1470) (I have created https://github.com/samvera-labs/ActiveTriples as a community fork for this), I would like to please propose one of two solutions:

- https://github.com/samvera-labs/ActiveTriples be considered a candidate for a core component
- A product owner be identified to serve for https://github.com/ActiveTriples/ActiveTriples in order to facilitate with the support for https://github.com/samvera/active_fedora

**Comment by jrgriffiniii** [comment]
In order to fulfill the promotion to core component status, the following requirements must be met:

- [ ] Code is stored in a repository in the Samvera github organization https://github.com/samvera and meets the [requirements](https://samvera.github.io/samvera_labs.html#guidelines-for-promotion-to-samvera-from-labs) for being there.
- [x] Component has a designated product owner.
- [ ] A participant of the [Component Maintenance Interest Group] must have a vested interest in the maintenance of that component, acting as a representative for their institution’s needs.

I can volunteer to serve as the product owner of this Gem.

**Comment by jrgriffiniii** [comment]
Investigating the contributors listed in the Google Sheet linked within https://samvera.atlassian.net/wiki/spaces/samvera/pages/405211659/Samvera+Licensed+Contributors, I am not finding https://github.com/mjsuhonos or https://github.com/eocarragain listed (or their respective institutions of Ryerson University and University College Cork). Perhaps they contributed when they were located in previous roles in other organizations?
