### ISSUE TITLE
Update the Samvera Logo referenced within the README for each component

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/maintenance#94]
There are currently README documents referencing the Samvera PNG logo image from the Wordpress site (https://samvera.org). These should, instead, reference the logo image uploaded to Confluence:

- [ ] [active_fedora](https://github.com/samvera/active_fedora)
- [ ] [bixby](https://github.com/samvera/bixby)
- [ ] [browse-everything](https://github.com/samvera/browse-everything)
- [ ] [hydra-derivatives](https://github.com/samvera/hydra-derivatives)
- [ ] [hydra-editor](https://github.com/samvera/hydra-editor)
- [ ] [hydra-file_characterization](https://github.com/samvera/hydra-file_characterization)
- [ ] [hydra-head](https://github.com/samvera/hydra-head)
- [ ] [hydra-pcdm](https://github.com/samvera/hydra-pcdm)
- [ ] [hydra-role-management](https://github.com/samvera/hydra-role-management)
- [ ] [hydra-works](https://github.com/samvera/hydra-works)
- [ ] [iiif_manifest](https://github.com/samvera/iiif_manifest)
- [ ] [ldp](https://github.com/samvera/ldp)
- [ ] [noid-rails](https://github.com/samvera/noid-rails)
- [ ] [questioning_authority](https://github.com/samvera/questioning_authority)
- [ ] [rubydora](https://github.com/samvera/rubydora)
- [ ] [samvera.github.io](https://github.com/samvera/samvera.github.io)
- [ ] [samvera-circleci-orb](https://github.com/samvera/samvera-circleci-orb)
- [ ] [valkyrie](https://github.com/samvera/valkyrie)
